let servicesJson = [
    {id:1, name: 'Planejamento de Irrigação', img:'thumb.jpg', price: 5000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Um serviço completo para projetar sistemas de irrigação eficientes. Inclui análise do terreno, seleção de equipamentos e planejamento para otimizar o uso de água, garantindo um jardim saudável e sustentável.'},
    {id:2, name: 'Manutenção de Jardins', img:'thumb.jpg', price: 3500.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Cuidado profissional para manter seu jardim impecável. Inclui poda, adubação, controle de pragas e limpeza, com opções personalizadas para atender às necessidades específicas do seu espaço verde.'},
    {id:3, name: 'Automação Elétrica', img:'thumb.jpg', price: 7000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Sistemas automatizados para controle de iluminação, irrigação e outros dispositivos no seu jardim. Projetado para maior eficiência e conveniência, com instalação profissional e suporte técnico.'},
    {id:4, name: 'Design de Jardins', img:'thumb.jpg', price: 6000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Transforme seu espaço com um projeto de paisagismo personalizado. Inclui seleção de plantas, layout estético e integração com sistemas de irrigação, criando um ambiente harmonioso e funcional.'},
    {id:5, name: 'Instalação de Sistemas de Irrigação', img:'thumb.jpg', price: 4500.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Instalação profissional de sistemas de irrigação automatizados ou manuais, garantindo cobertura eficiente e durabilidade. Inclui testes e ajustes para desempenho ideal.'},
    {id:6, name: 'Manutenção Elétrica para Jardins', img:'thumb.jpg', price: 4000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Serviço especializado em manutenção de sistemas elétricos em jardins, incluindo iluminação externa e controles automatizados. Garante segurança e funcionamento contínuo.'},
    {id:7, name: 'Consultoria em Sustentabilidade', img:'thumb.jpg', price: 3000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Orientação profissional para tornar seu jardim mais sustentável. Inclui análise de consumo de água, seleção de plantas nativas e recomendações para reduzir o impacto ambiental.'},
    {id:8, name: 'Reforma de Jardins', img:'thumb.jpg', price: 8000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Revitalize seu jardim com uma reforma completa. Inclui remoção de elementos antigos, replantio, instalação de novos sistemas e redesign para um visual moderno e funcional.'},
    {id:9, name: 'Automação Avançada', img:'thumb.jpg', price: 10000.00, scopes: ['Básico', 'Intermediário', 'Avançado'], description: 'Soluções de automação de ponta para jardins, integrando sensores, controles remotos e sistemas inteligentes. Ideal para projetos sofisticados que buscam máxima eficiência e inovação.'}
];